# Generated by Django 3.2.3 on 2021-05-28 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(max_length=100)),
                ('icing_flavor', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tasting date')),
                ('tasted', models.CharField(choices=[('H', 'Homemade'), ('B', 'Bakery'), ('S', 'Storebought'), ('E', 'Elsewhere')], default='H', max_length=1, verbose_name='Cake Origin')),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cake')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cake')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='customizations',
            field=models.ManyToManyField(blank=True, to='main_app.Customization'),
        ),
        migrations.AddField(
            model_name='cake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
