# Generated by Django 3.2.3 on 2021-05-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='icing_flavor',
            field=models.CharField(default='vanilla', max_length=100),
            preserve_default=False,
        ),
    ]
