# Generated by Django 3.2.3 on 2021-05-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cake_icing_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
