# Generated by Django 3.2.3 on 2021-05-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cake_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='background_image',
        ),
    ]
