# Generated by Django 3.2.3 on 2021-05-26 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_cake_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasted', models.CharField(choices=[('H', 'Homemade'), ('B', 'Bakery'), ('S', 'Storebought'), ('E', 'Elsewhere')], default='H', max_length=1)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cake')),
            ],
        ),
    ]
