# Generated by Django 3.2.3 on 2021-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_tasting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tasting',
            name='date',
            field=models.DateField(verbose_name='Tasting date'),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='tasted',
            field=models.CharField(choices=[('H', 'Homemade'), ('B', 'Bakery'), ('S', 'Storebought'), ('E', 'Elsewhere')], default='H', max_length=1, verbose_name='Cake Origin'),
        ),
        migrations.AddField(
            model_name='cake',
            name='customizations',
            field=models.ManyToManyField(blank=True, to='main_app.Customization'),
        ),
    ]
